apiVersion: v1
kind: Service
metadata:
  name: selenium-node-firefox
  labels:
    app: selenium
spec:
  selector:
    app: selenium
    component: node-firefox
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP

