apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-xss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-xss
  template:
    metadata:
      labels:
        app: hello-xss
    spec:
      containers:
        - name: hello-xss
          image: nginx
          ports:
            - containerPort: 8000

